[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.18.2"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9.0"
actix-web = "4.1.0"
actix-cors = "0.6.2"
serde_json = "1.0.107"
sunscreen = "0.8.1"
